[build]
  command = "echo 'Building kubeview frontend...'"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  GO_VERSION = "1.21"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
