apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kubeview
  labels:
    app: {{ .Release.Name }}-kubeview
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-kubeview
